/**
 * Installer + doctor lifecycle across the three harnesses (Claude Code,
 * OpenCode, Codex).
 *
 * Every test builds its own fixture in a temp dir. Nothing here reads the
 * repo's skills, because those are regenerated by other tooling and would make
 * the suite flap. The hook adapters and MCP configs ARE copied from the repo:
 * they are the committed contract the engine validates, not generated output.
 */

import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

import { afterEach, describe, expect, test } from 'bun:test';

import { diagnoseAgentCompatibility } from './doctor.ts';
import {
  buildCommunitySkillArgs,
  describeAgentDetection,
  detectAgents,
  discoverRequiredEnvVars,
  mergedHarnesses,
  migrateAgentIds,
  parseAgentsEnv,
  PROJECT_SKILL_DESTINATION,
  recordHarnessSelection,
  repairRepositoryCompatibility,
} from './install.ts';
import { declaredMcpIds } from './lib/agent-compatibility-contracts.ts';
import { CLAUDE_INSTRUCTIONS_SHIM, claudeSkillsAliasPlan, repairClaudeSkillsAlias } from './lib/agent-compatibility.ts';

const REPO_ROOT = resolve(import.meta.dir, '..');
const temporaryRoots: string[] = [];

function temporaryRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'agent-lifecycle-'));
  temporaryRoots.push(root);
  return root;
}

function write(root: string, relativePath: string, content: string): void {
  const destination = join(root, relativePath);
  mkdirSync(dirname(destination), { recursive: true });
  writeFileSync(destination, content);
}

function copyFromRepo(root: string, relativePath: string): void {
  const destination = join(root, relativePath);
  mkdirSync(dirname(destination), { recursive: true });
  cpSync(join(REPO_ROOT, relativePath), destination, { recursive: true });
}

/**
 * A project on one harness deletes the other harnesses' files (ADR-0013), so
 * the fixture copies what this checkout has, and a test that reads a dropped
 * harness skips.
 */
const HAS_CODEX = existsSync(join(REPO_ROOT, '.codex/hooks.json')) && existsSync(join(REPO_ROOT, '.codex/config.toml'));
const HAS_CLAUDE = existsSync(join(REPO_ROOT, 'CLAUDE.md'));
const HAS_ALL_HARNESSES = HAS_CODEX && HAS_CLAUDE && existsSync(join(REPO_ROOT, 'opencode.jsonc')) && existsSync(join(REPO_ROOT, '.opencode/plugins/personality-reinject.js'));

/**
 * A repo that satisfies the whole contract EXCEPT the generated `.claude/skills`
 * alias, which `repairRepositoryCompatibility` is expected to create.
 */
function compatibilityFixture(): string {
  const root = temporaryRoot();
  write(root, 'AGENTS.md', '# AGENTS.md\n\nCanonical instructions.\n');
  if (HAS_CLAUDE) { write(root, 'CLAUDE.md', CLAUDE_INSTRUCTIONS_SHIM); }
  write(root, '.agents/skills/project-context/SKILL.md', '---\nname: project-context\n---\n\nModes: `data`, `dev-roadmap`.\n');
  for (const path of [
    '.agents/hooks/personality-reinject.mjs',
    '.claude/settings.json',
    '.opencode/plugins/personality-reinject.js',
    '.codex/hooks.json',
    '.codex/config.toml',
    '.mcp.json',
    'opencode.jsonc',
  ].filter(path => existsSync(join(REPO_ROOT, path)))) { copyFromRepo(root, path); }
  return root;
}

afterEach(() => {
  while (temporaryRoots.length > 0) {
    const root = temporaryRoots.pop();
    if (root) { rmSync(root, { recursive: true, force: true }); }
  }
});

describe('installer harness detection', () => {
  test('parses INSTALL_AGENTS for the three ids, drops unknowns and duplicates', () => {
    expect(parseAgentsEnv('codex,claude-code,codex,unknown,opencode')).toEqual([
      'codex',
      'claude-code',
      'opencode',
    ]);
    expect(parseAgentsEnv('')).toBeNull();
    expect(parseAgentsEnv(undefined)).toBeNull();
    expect(parseAgentsEnv('nothing-valid')).toEqual([]);
    expect(migrateAgentIds(['claude-code', 'opencode'])).toEqual(['claude-code', 'opencode']);
    expect(migrateAgentIds(['codex', 'unknown', 'codex'])).toEqual(['codex']);
    expect(migrateAgentIds('codex')).toEqual([]);
  });

  test('detects Claude Code and OpenCode from their home config directories', async () => {
    const root = temporaryRoot();
    const home = join(root, 'home');
    mkdirSync(join(home, '.claude'), { recursive: true });
    mkdirSync(join(home, '.config', 'opencode'), { recursive: true });

    const detected = await detectAgents({ home, root, binaryExists: () => false });
    expect(detected).toEqual({
      claudeCode: true,
      opencode: true,
      codexCli: false,
      codexConfigured: false,
    });
  });

  test('distinguishes the Codex CLI from a Desktop-only repository configuration', async () => {
    const root = temporaryRoot();
    write(root, '.codex/config.toml', '[shell_environment_policy]\ninherit = "core"\n');

    const cliAndConfig = await detectAgents({ home: join(root, 'home'), root, binaryExists: binary => binary === 'codex' });
    expect(cliAndConfig).toEqual({ claudeCode: false, opencode: false, codexCli: true, codexConfigured: true });
    expect(describeAgentDetection(cliAndConfig)).toContain('Codex: CLI found');

    const configOnly = await detectAgents({ home: join(root, 'home'), root, binaryExists: () => false });
    expect(configOnly).toMatchObject({ codexCli: false, codexConfigured: true });
    expect(describeAgentDetection(configOnly)).toContain('repository configured for Desktop');

    const nothing = await detectAgents({ home: join(root, 'home'), root: join(root, 'empty'), binaryExists: () => false });
    expect(nothing).toEqual({ claudeCode: false, opencode: false, codexCli: false, codexConfigured: false });
    expect(describeAgentDetection(nothing)).toContain('Codex: not found');
  });

  test('falls back to the PATH lookup when no home config directory exists', async () => {
    // The PATH probe is injectable (`binaryExists`) because Bun's spawnSync does
    // not reliably observe a mutated `process.env.PATH`; the branch under test is
    // "directory absent -> executable decides", which this exercises exactly.
    const root = temporaryRoot();
    const probed: string[] = [];
    const detected = await detectAgents({
      home: join(root, 'home'),
      root,
      binaryExists: (binary) => {
        probed.push(binary);
        return binary === 'claude' || binary === 'codex';
      },
    });
    expect(probed.sort()).toEqual(['claude', 'codex', 'opencode']);
    expect(detected).toEqual({ claudeCode: true, opencode: false, codexCli: true, codexConfigured: false });
  });
});

describe('installer skill and env contracts', () => {
  test('keeps project skills in the canonical store and maps global skills to every harness', () => {
    const item = { package: 'owner/repo', skill: 'example' };
    expect(PROJECT_SKILL_DESTINATION).toBe('.agents/skills');
    expect(buildCommunitySkillArgs(item, 'project', ['claude-code', 'opencode', 'codex']))
      .toEqual(['skills', 'add', 'owner/repo', '--skill', 'example', '--yes']);
    expect(buildCommunitySkillArgs({ package: 'owner/all', skill: '*' }, 'project', ['codex']))
      .toEqual(['skills', 'add', 'owner/all', '--yes']);
    expect(buildCommunitySkillArgs(item, 'global', ['claude-code', 'opencode', 'codex']))
      .toEqual([
        'skills',
        'add',
        'owner/repo',
        '--skill',
        'example',
        '--global',
        '--agent',
        'claude-code',
        '--agent',
        'opencode',
        '--agent',
        'codex',
        '--yes',
      ]);
  });

  test('discovers the env-var union across the selected harnesses', async () => {
    const root = temporaryRoot();
    // Claude Code placeholders are literal `${VAR}` text in .mcp.json by design.
    // eslint-disable-next-line no-template-curly-in-string
    const claudePlaceholders = { CLAUDE_ONLY_KEY: '${CLAUDE_ONLY_KEY}', SHARED_TOKEN: '${SHARED_TOKEN:-x}' };
    write(root, '.mcp.json', JSON.stringify({ mcpServers: { a: { env: claudePlaceholders } } }));
    write(root, 'opencode.jsonc', '{\n  // comment\n  "mcp": { "a": { "environment": { "SHARED_TOKEN": "{env:SHARED_TOKEN}", "OPENCODE_ONLY_KEY": "{env:OPENCODE_ONLY_KEY}" } } }\n}\n');
    write(root, '.codex/config.toml', [
      '[mcp_servers.tavily]',
      'url = "https://example.invalid/mcp"',
      'bearer_token_env_var = "SHARED_TOKEN"',
      '',
      '[mcp_servers.supabase]',
      'command = "bunx"',
      'env_vars = ["CODEX_ONLY_KEY", "SHARED_TOKEN"]',
      '',
      '[mcp_servers.supabase.env]',
      'LOG_LEVEL = "error"',
      'NOT_A_SECRET = "literal"',
      '',
    ].join('\n'));

    expect(await discoverRequiredEnvVars(['codex'], root)).toEqual(['CODEX_ONLY_KEY', 'SHARED_TOKEN']);
    expect(await discoverRequiredEnvVars(['claude-code'], root)).toEqual(['CLAUDE_ONLY_KEY', 'SHARED_TOKEN']);
    expect(await discoverRequiredEnvVars(['claude-code', 'opencode', 'codex'], root)).toEqual([
      'CLAUDE_ONLY_KEY',
      'CODEX_ONLY_KEY',
      'OPENCODE_ONLY_KEY',
      'SHARED_TOKEN',
    ]);
    expect(await discoverRequiredEnvVars([], root)).toEqual([]);
  });

  test('discovers the names a .env loader --filter lists, on every host', async () => {
    const root = temporaryRoot();
    const loader = ['-p', 'varlock@1.20.0', 'varlock', 'run', '--no-redact-stdout', '--inject', 'vars', '--filter'];
    write(root, '.mcp.json', JSON.stringify({ mcpServers: { a: { command: 'bunx', args: [...loader, 'TOKEN_A,URL_B', '--', 'npx', 'pkg'] } } }));
    write(root, 'opencode.jsonc', `{\n  // "--filter", "COMMENTED_OUT"\n  "mcp": { "a": { "command": ["bunx", ${[...loader, 'TOKEN_A,URL_B', '--'].map(a => JSON.stringify(a)).join(', ')}, "npx", "pkg",] } },\n}\n`);
    write(root, '.codex/config.toml', [
      '# args = ["--filter", "COMMENTED_OUT"]',
      '[mcp_servers.a]',
      'command = "bunx"',
      `args = [${[...loader, 'TOKEN_A,URL_B', '--', 'npx', 'pkg'].map(a => JSON.stringify(a)).join(', ')}]`,
      '',
    ].join('\n'));

    for (const agent of ['claude-code', 'opencode', 'codex'] as const) {
      expect(await discoverRequiredEnvVars([agent], root)).toEqual(['TOKEN_A', 'URL_B']);
    }
  });
});

describe('installer harness selection (ADR-0013)', () => {
  test('the selection is added to the declared list, never shrinks it', () => {
    expect(mergedHarnesses([], ['claude-code'])).toEqual(['claude']);
    expect(mergedHarnesses(['codex', 'claude'], ['claude-code', 'opencode'])).toEqual(['codex', 'claude', 'opencode']);
    expect(mergedHarnesses(['opencode'], [])).toEqual(['opencode']);
  });

  test('records the selection in project.yaml and keeps the unused files unless the offer is accepted', async () => {
    const root = temporaryRoot();
    write(root, 'package.json', JSON.stringify({ name: 'my-dev-project' }));
    write(root, '.agents/project.yaml', 'project:\n  project_name: X\nharnesses: null # detect\n');
    for (const path of ['.mcp.json', 'opencode.jsonc', '.codex/config.toml', '.codex/hooks.json']) { write(root, path, '{}\n'); }

    const asked: string[] = [];
    await recordHarnessSelection(['claude-code'], root, async (message) => {
      asked.push(message);
      return message.startsWith('Codex');
    });
    expect(readFileSync(join(root, '.agents/project.yaml'), 'utf8')).toBe('project:\n  project_name: X\nharnesses: [claude] # detect\n');
    expect(asked).toHaveLength(2);
    expect(existsSync(join(root, 'opencode.jsonc'))).toBe(true);
    expect(existsSync(join(root, '.codex'))).toBe(false);
  });

  test('leaves the boilerplate alone: it checks all three', async () => {
    const root = temporaryRoot();
    write(root, 'package.json', JSON.stringify({ name: 'agentic-dev-boilerplate' }));
    write(root, '.agents/project.yaml', 'harnesses: null\n');
    await recordHarnessSelection(['opencode'], root, async () => { throw new Error('must not ask'); });
    expect(readFileSync(join(root, '.agents/project.yaml'), 'utf8')).toBe('harnesses: null\n');
  });
});

describe('compatibility repair lifecycle', () => {
  test('constructs portable POSIX and Windows alias plans', () => {
    const root = temporaryRoot();
    expect(claudeSkillsAliasPlan(root, 'linux')).toMatchObject({ target: '../.agents/skills', type: 'symlink' });
    expect(claudeSkillsAliasPlan(root, 'win32')).toMatchObject({ target: join(root, '.agents', 'skills'), type: 'junction' });
  });

  test.skipIf(!HAS_CLAUDE)('creates the alias and generates no command file, then is a no-op on the second run', () => {
    const root = compatibilityFixture();
    const first = repairRepositoryCompatibility(root, 'linux');
    expect(first).toMatchObject({ shadowingCommandsMoved: [], alias: { status: 'created' } });
    // A skill is invoked by its own name plus a mode: no wrapper is rendered.
    expect(existsSync(join(root, '.claude/commands'))).toBe(false);
    expect(existsSync(join(root, '.opencode/commands'))).toBe(false);
    // The alias makes the canonical skill visible where Claude Code looks.
    expect(readFileSync(join(root, '.claude/skills/project-context/SKILL.md'), 'utf8')).toContain('name: project-context');

    const second = repairRepositoryCompatibility(root, 'linux');
    expect(second).toMatchObject({ shadowingCommandsMoved: [], alias: { status: 'valid' } });
  });

  test.skipIf(!HAS_CLAUDE)('moves a command that shadows a skill out of the way and keeps a project command', () => {
    const root = compatibilityFixture();
    write(root, '.claude/commands/project-context.md', 'Do it my way.\n');
    write(root, '.opencode/commands/deploy.md', 'A project command with its own name.\n');

    const repair = repairRepositoryCompatibility(root, 'linux');
    expect(repair.shadowingCommandsMoved).toEqual(['.claude/commands/project-context.md']);
    expect(existsSync(join(root, '.claude/commands/project-context.md'))).toBe(false);
    expect(readFileSync(join(root, '.backups/shadowing-commands/.claude/commands/project-context.md'), 'utf8')).toBe('Do it my way.\n');
    expect(readFileSync(join(root, '.opencode/commands/deploy.md'), 'utf8')).toBe('A project command with its own name.\n');
  });

  test.skipIf(!HAS_CLAUDE)('reclaims the skills CLI per-skill symlink shim without losing a skill body', () => {
    const root = compatibilityFixture();
    mkdirSync(join(root, '.claude/skills'), { recursive: true });
    symlinkSync('../../.agents/skills/project-context', join(root, '.claude/skills/project-context'), 'dir');

    expect(repairRepositoryCompatibility(root, 'linux').alias?.status).toBe('repaired');
    expect(readFileSync(join(root, '.agents/skills/project-context/SKILL.md'), 'utf8')).toContain('name: project-context');
    expect(readFileSync(join(root, '.claude/skills/project-context/SKILL.md'), 'utf8')).toContain('name: project-context');
  });

  test.skipIf(!HAS_CLAUDE)('refuses to replace a real Claude skills directory and keeps its content', () => {
    const root = compatibilityFixture();
    mkdirSync(join(root, '.claude/skills'), { recursive: true });
    writeFileSync(join(root, '.claude/skills/owned.txt'), 'preserve me\n');

    expect(() => repairClaudeSkillsAlias(root, 'linux')).toThrow('Refusing to replace');
    expect(() => repairRepositoryCompatibility(root, 'linux')).toThrow('Refusing to replace');
    expect(readFileSync(join(root, '.claude/skills/owned.txt'), 'utf8')).toBe('preserve me\n');
  });

  test.skipIf(!HAS_CODEX)('surfaces contract errors the repair cannot fix', () => {
    const root = compatibilityFixture();
    rmSync(join(root, '.codex/hooks.json'));

    expect(() => repairRepositoryCompatibility(root, 'linux')).toThrow('Hook compatibility file missing: .codex/hooks.json');
  });
});

describe('doctor diagnosis', () => {
  test.skipIf(!HAS_ALL_HARNESSES)('reports a compliant fixture as file-correct, with trust as unverifiable runtime state', () => {
    const root = compatibilityFixture();
    repairRepositoryCompatibility(root, 'linux');
    const diagnostic = diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: false });

    expect(diagnostic.file_correct).toBe(true);
    expect(diagnostic.errors).toEqual([]);
    expect(diagnostic.instructions).toEqual({ agents_md: true, claude_shim: true, canonical_skills: true, claude_alias: true });
    expect(diagnostic.hooks).toEqual({ claude: true, opencode: true, codex: true, ok: true });
    expect(diagnostic.mcp).toEqual({
      expected_servers: declaredMcpIds(root).length,
      claude: true,
      opencode: true,
      codex: true,
      parity: true,
    });
    expect(diagnostic.codex).toEqual({
      config_exists: true,
      cli_detected: false,
      repository_configured: true,
      desktop_uses_repository_config: true,
      trust_required: true,
      trust_status: 'required-not-verifiable',
    });
  });

  test.skipIf(!HAS_CLAUDE || !HAS_CODEX)('flags a CLAUDE.md that is not the exact shim', () => {
    const root = compatibilityFixture();
    repairRepositoryCompatibility(root, 'linux');
    writeFileSync(join(root, 'CLAUDE.md'), '# Real instructions\n\nNot a shim.\n');

    const diagnostic = diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: true });
    expect(diagnostic.file_correct).toBe(false);
    expect(diagnostic.instructions.claude_shim).toBe(false);
    expect(diagnostic.instructions.agents_md).toBe(true);
    expect(diagnostic.errors.some(error => error.includes('CLAUDE.md must contain exactly'))).toBe(true);
    expect(diagnostic.codex.cli_detected).toBe(true);
  });

  test('flags a command that shadows a skill, and the repair clears it', () => {
    const root = compatibilityFixture();
    repairRepositoryCompatibility(root, 'linux');
    write(root, '.opencode/commands/project-context.md', 'Do it my way.\n');

    const diagnostic = diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: false });
    expect(diagnostic.file_correct).toBe(false);
    expect(diagnostic.errors).toContainEqual(expect.stringContaining('Command shadows skill project-context: .opencode/commands/project-context.md'));

    expect(repairRepositoryCompatibility(root, 'linux').shadowingCommandsMoved).toEqual(['.opencode/commands/project-context.md']);
    expect(diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: false }).file_correct).toBe(true);
  });

  test.skipIf(!HAS_ALL_HARNESSES)('reports a missing alias and missing Codex config without throwing', () => {
    const root = compatibilityFixture();
    // Declared, so deleting every Codex file is drift, not a retired harness.
    write(root, '.agents/project.yaml', 'harnesses: [claude, opencode, codex]\n');
    rmSync(join(root, '.codex'), { recursive: true, force: true });

    const diagnostic = diagnoseAgentCompatibility(root, { platform: 'linux', codexCliDetected: false });
    expect(diagnostic.file_correct).toBe(false);
    expect(diagnostic.instructions.claude_alias).toBe(false);
    expect(diagnostic.hooks.codex).toBe(false);
    expect(diagnostic.mcp.codex).toBe(false);
    expect(diagnostic.codex).toMatchObject({ config_exists: false, repository_configured: false });
  });
});
