import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { afterEach, describe, expect, test } from 'bun:test';
import {
  analyzeIsolation,
  eslintIsolation,
  isolationFindings,
  isolationPrompt,
  parseJsonc,
  tsconfigIsolation,
  tsGlobMatches,
} from './adopt-isolation.ts';
import { detectHookManager } from './hook-manager.ts';

const roots: string[] = [];
function tempRoot(files: Record<string, string> = {}): string {
  const root = mkdtempSync(join(tmpdir(), 'adopt isolation '));
  roots.push(root);
  for (const [rel, text] of Object.entries(files)) {
    mkdirSync(dirname(join(root, rel)), { recursive: true });
    writeFileSync(join(root, rel), text);
  }
  return root;
}
afterEach(() => {
  while (roots.length > 0) { rmSync(roots.pop()!, { recursive: true, force: true }); }
});

// create-next-app's tsconfig, comments and a trailing comma included.
const NEXT_TSCONFIG = `{
  // generated by create-next-app
  "compilerOptions": { "strict": true, "paths": { "@/*": ["./*"] }, },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

describe('parseJsonc + tsGlobMatches', () => {
  test('comments and trailing commas parse; a "//" inside a string survives', () => {
    expect(parseJsonc('{ "a": "http://x", /* c */ "b": [1,], }')).toEqual({ a: 'http://x', b: [1] });
    expect(parseJsonc('{ nope')).toBeNull();
  });

  test('tsconfig wildcard semantics: **/ never enters a dot-directory, a bare name is a directory', () => {
    expect(tsGlobMatches('**/*.ts', 'cli/lib/x.ts')).toBe(true);
    expect(tsGlobMatches('**/*.ts', '.agents/skills/x.ts')).toBe(false);
    expect(tsGlobMatches('**/*.tsx', 'cli/x.ts')).toBe(false);
    expect(tsGlobMatches('scripts', 'scripts/lib/x.ts')).toBe(true);
    expect(tsGlobMatches('./scripts/**', 'scripts/x.ts')).toBe(true);
    expect(tsGlobMatches('src', 'scripts/x.ts')).toBe(false);
  });
});

describe('tsconfigIsolation', () => {
  test('a stock Next tsconfig reaches both tooling dirs; the exclude keeps the app entries first', () => {
    const t = tsconfigIsolation(tempRoot({ 'tsconfig.json': NEXT_TSCONFIG }));
    expect(t).toEqual({ path: 'tsconfig.json', reached: ['cli', 'scripts'], exclude: ['node_modules', 'cli', 'scripts'] });
  });

  test('an app that already excludes scripts/** (the measured webapp) is only missing cli', () => {
    const tsconfig = NEXT_TSCONFIG.replace('"exclude": ["node_modules"]', '"exclude": ["node_modules", "scripts/**"]');
    expect(tsconfigIsolation(tempRoot({ 'tsconfig.json': tsconfig }))?.exclude).toEqual(['node_modules', 'scripts/**', 'cli']);
  });

  test('null when the tooling is already out, the program is files-only or src-only, or there is no tsconfig', () => {
    const done = NEXT_TSCONFIG.replace('"exclude": ["node_modules"]', '"exclude": ["node_modules", "cli", "scripts"]');
    expect(tsconfigIsolation(tempRoot({ 'tsconfig.json': done }))).toBeNull();
    expect(tsconfigIsolation(tempRoot({ 'tsconfig.json': '{ "files": ["a.ts"] }' }))).toBeNull();
    expect(tsconfigIsolation(tempRoot({ 'tsconfig.json': '{ "include": ["src"] }' }))).toBeNull();
    expect(tsconfigIsolation(tempRoot())).toBeNull();
  });

  test('no include and no exclude: TypeScript\'s defaults, restated when exclude is written', () => {
    expect(tsconfigIsolation(tempRoot({ 'tsconfig.json': '{}' }))?.exclude).toEqual(['node_modules', 'cli', 'scripts']);
  });
});

describe('eslintIsolation', () => {
  test('a flat config without ignores misses every tooling path', () => {
    const e = eslintIsolation(tempRoot({ 'eslint.config.mjs': 'export default [];\n' }));
    expect(e).toEqual({ path: 'eslint.config.mjs', kind: 'flat', missing: ['cli/**', 'scripts/**', 'eslint.config.base.js', 'eslint.config.tooling.mjs'] });
  });

  test('quoted literals in the config or lines of .eslintignore count; prose and comments do not', () => {
    const root = tempRoot({
      'eslint.config.mjs': '// cli/** is ignored below? no\nexport default [{ ignores: [\'cli/**\', "./scripts/", \'eslint.config.base.js\'] }];\n',
      '.eslintignore': 'eslint.config.tooling.mjs\n',
    });
    expect(eslintIsolation(root)).toBeNull();
    const prose = tempRoot({ 'eslint.config.mjs': '// ignores: [\'cli/**\', \'scripts/**\']\nconst cli = 1;\nexport default [];\n' });
    expect(eslintIsolation(prose)?.missing).toContain('cli/**');
  });

  test('legacy configs and package.json eslintConfig are found; no config at all is null', () => {
    expect(eslintIsolation(tempRoot({ '.eslintrc.json': '{}' }))?.kind).toBe('legacy');
    expect(eslintIsolation(tempRoot({ 'package.json': '{"eslintConfig":{}}' }))?.path).toBe('package.json');
    expect(eslintIsolation(tempRoot({ 'package.json': '{}' }))).toBeNull();
  });
});

describe('isolationFindings + isolationPrompt', () => {
  test('one BLOCKING row per app config and for an unwired foreign hook manager, every snippet in one saved file', () => {
    const root = tempRoot({ 'tsconfig.json': NEXT_TSCONFIG, '.eslintrc.json': '{}', 'lefthook.yml': 'pre-commit: {}\n' });
    const a = analyzeIsolation(root, detectHookManager(root, null));
    const rows = isolationFindings(a, '.agents/prompts/adopt-tooling-isolation.md');
    expect(rows.map(r => [r.path, r.blocking, r.suggested])).toEqual([
      ['tsconfig.json', true, 'decide'],
      ['.eslintrc.json', true, 'decide'],
      ['lefthook.yml', true, 'decide'],
    ]);
    expect(rows[0].detail).toContain('"exclude": ["node_modules","cli","scripts"]');
    expect(rows[1].detail).toContain('"ignorePatterns": ["cli/","scripts/","eslint.config.base.js","eslint.config.tooling.mjs"]');
    expect(rows[2].evidence).toContain('husky is NOT installed');
    const prompt = isolationPrompt(a)!;
    expect(prompt).toContain('## tsconfig.json');
    expect(prompt).toContain('## .eslintrc.json');
    expect(prompt).toContain('## Hooks (lefthook: lefthook.yml)');
  });

  test('a greenfield-shaped repo (husky, no app configs reaching the tooling) has nothing to say', () => {
    const root = tempRoot({ '.husky/pre-commit': 'x', 'tsconfig.json': '{ "include": ["src"] }' });
    const a = analyzeIsolation(root, detectHookManager(root, null));
    expect(isolationFindings(a, null)).toEqual([]);
    expect(isolationPrompt(a)).toBeNull();
  });
});
