/**
 * @fileoverview The business context maps: one HTML file per shipped context
 * skill, the single source of a synthesis a human opens in a browser and an AI
 * reads through `bun run context:map` (scripts/context-map.ts).
 *
 * Principle (`agentic-dev-core/references/skill-scaffold.md` §3): `.context/`
 * holds what a SCRIPT pulls from a source of truth plus what this repo itself
 * is the source of truth for (PRD, SRS, ADRs, the domain glossary); what an AI
 * SYNTHESIZES from code, schema and contracts lives in a skill. The business
 * data, feature and API maps are synthesis, so each one lives inside its own
 * context skill at `references/<map>.html`, generated by a `project-context`
 * mode and edited section by section afterwards.
 *
 * This module is the ONE list of those skills, shared by the reader, the
 * updater (bootstrap delivery + informational parity rows) and the doctor.
 * Import-closed: node builtins only, so `scripts/` imports it, never the other
 * way round.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

export interface ContextMapSkill {
  /** Skill slug under `.agents/skills/`. */
  slug: string
  /** File name of the map inside the skill's `references/`. */
  map: string
  /** The skill step that generates the map, as a user runs it (`project-context mode data`). */
  generator: string
  /**
   * The markdown files this map replaces, kept in a project and read as
   * generator input. Never deleted by anything upstream ships.
   */
  legacy: readonly string[]
}

/**
 * Context skills upstream ships as placeholders. Unlike every other
 * `<aspect>-context` (project-local by construction, `isProjectLocalSkillPath`),
 * the updater DELIVERS each of these once when its folder is absent, then never
 * overwrites or deletes it: the map inside is the project's own synthesis.
 */
export const CONTEXT_MAP_SKILLS: readonly ContextMapSkill[] = [
  { slug: 'business-data-context', map: 'business-data-map.html', generator: 'project-context mode data', legacy: ['.context/business/business-data-map.md'] },
  { slug: 'business-feature-context', map: 'business-feature-map.html', generator: 'project-context mode features', legacy: ['.context/business/business-feature-map.md'] },
  { slug: 'business-api-context', map: 'business-api-map.html', generator: 'project-context mode api', legacy: ['.context/business/business-api-map.md'] },
];

export const CONTEXT_MAP_SLUGS: ReadonlySet<string> = new Set(CONTEXT_MAP_SKILLS.map(s => s.slug));

/** Line 1 of a map that has not been generated yet. */
export const PLACEHOLDER_BANNER_PREFIX = '<!-- placeholder:';
/** Line 1 of a generated map (`<!-- generated by <generator>; ... -->`). */
export const GENERATED_BANNER_PREFIX = '<!-- generated by ';

export function contextMapSkill(slug: string): ContextMapSkill | undefined {
  return CONTEXT_MAP_SKILLS.find(s => s.slug === slug);
}

/** Repo-relative path of a skill's map, forward slashes. */
export function mapRelPath(skill: ContextMapSkill, skillsDir = '.agents/skills'): string {
  return `${skillsDir.replace(/\\/g, '/').replace(/\/+$/, '')}/${skill.slug}/references/${skill.map}`;
}

/** True when the HTML is a placeholder map (banner on its first non-empty line). */
export function isPlaceholderMap(html: string): boolean {
  const first = html.replace(/^\uFEFF/, '').trimStart().split(/\r?\n/, 1)[0] ?? '';
  return first.startsWith(PLACEHOLDER_BANNER_PREFIX);
}

export type MapState = 'no-skill' | 'no-map' | 'placeholder' | 'generated';

export interface MapStatus {
  skill: ContextMapSkill
  state: MapState
  /** The legacy markdown files that exist beside a missing or placeholder HTML map. */
  legacyPresent: readonly string[]
}

/** State of every shipped context map in a repo. Read-only. */
export function contextMapStatuses(repoRoot: string): MapStatus[] {
  return CONTEXT_MAP_SKILLS.map((skill) => {
    const skillDir = join(repoRoot, '.agents', 'skills', skill.slug);
    const mapPath = join(skillDir, 'references', skill.map);
    let state: MapState;
    if (!existsSync(skillDir)) { state = 'no-skill'; }
    else if (!existsSync(mapPath)) { state = 'no-map'; }
    else { state = isPlaceholderMap(readFileSync(mapPath, 'utf8')) ? 'placeholder' : 'generated'; }
    const legacyPresent = state === 'generated'
      ? []
      : skill.legacy.filter(rel => existsSync(join(repoRoot, ...rel.split('/'))));
    return { skill, state, legacyPresent };
  });
}

/** One human line per map that still needs generating; null when the map is generated or its skill is absent. */
export function contextMapAdvice(status: MapStatus): string | null {
  if (status.state === 'generated' || status.state === 'no-skill') { return null; }
  const what = status.state === 'no-map' ? 'has no map' : 'holds a placeholder map';
  const old = status.legacyPresent.map(rel => `\`${rel}\``).join(', ');
  const legacy = status.legacyPresent.length === 0
    ? ''
    : `; your old ${old} ${status.legacyPresent.length === 1 ? 'is' : 'are'} kept and will be read as input`;
  return `\`${status.skill.slug}\` ${what}${legacy}: run \`${status.skill.generator}\``;
}
