import type { AdoptHookInput } from './updater-adopt.ts';
import type { PackageJsonDelta } from './updater-types';
import { existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';

import { afterEach, describe, expect, test } from 'bun:test';
import { parse as parseYaml } from 'yaml';
import { CLAUDE_INSTRUCTIONS_SHIM } from './agent-compatibility.ts';
import {
  ADOPT_ENV_SENTINEL,
  ADOPT_INSTRUCTIONS_HEADING,
  ADOPT_INSTRUCTIONS_PROMPT,
  ADOPT_REPO_ONLY_PATTERNS,
  adoptFindings,
  appendEnvExampleBlock,
  CANONICAL_TEMPLATE,
  composeAdoptedInstructions,
  envDeclaredKeys,
  INSTALLER_LOCK_FILE,
  isAdopted,
  planAdoptInstructions,
  runAdopt,
  scriptCompositionProposal,
  seedAdoptedProjectYaml,
  withProtectedPaths,
  writeInstallerLock,
} from './updater-adopt.ts';
import { adoptPackageJsonDelta } from './updater-package.ts';

const roots: string[] = [];
function tempRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'updater adopt '));
  roots.push(root);
  return root;
}
function write(root: string, rel: string, text: string): void {
  mkdirSync(dirname(join(root, rel)), { recursive: true });
  writeFileSync(join(root, rel), text);
}
function read(root: string, rel: string): string {
  return readFileSync(join(root, rel), 'utf8');
}
afterEach(() => {
  while (roots.length > 0) { rmSync(roots.pop()!, { recursive: true, force: true }); }
});

const UPSTREAM_AGENTS = '# AGENTS.md: AI Persistent Memory\n\n> header\n\n---\n\n## 1. CRITICAL RULES\n\n1. rule\n\n## 2. BEHAVIOR\n';
const SCHEMA = '# GENERATED by `bun run agents:schema`. DO NOT EDIT BY HAND.\n\nproject:\n  project_name: null # TODO\n\nupdater:\n  protected_paths: [] # e.g. [scripts/lint-vars.ts]\n';

describe('ADOPT_REPO_ONLY_PATTERNS', () => {
  test('the boilerplate\'s numbered ADRs stay out; README and the template travel', () => {
    const excluded = (p: string): boolean => ADOPT_REPO_ONLY_PATTERNS.some(re => re.test(p));
    expect(excluded('.context/ADR/ADR-0002-multi-harness-single-source.md')).toBe(true);
    expect(excluded('.context/ADR/README.md')).toBe(false);
    expect(excluded('.context/ADR/ADR-NNNN-template.md')).toBe(false);
  });
});

describe('.env.example', () => {
  test('declared keys include commented and exported declarations', () => {
    expect([...envDeclaredKeys('A=1\n# B=\nexport C=x\n# just a comment\nlower=1\n')]).toEqual(['A', 'B', 'C']);
  });

  test('appends only the missing keys, inside one sentinel block, never touching the app lines', () => {
    const local = 'NEXT_PUBLIC_SUPABASE_URL=https://app.example\nAPP_SECRET=\n';
    const upstream = '# Supabase\nNEXT_PUBLIC_SUPABASE_URL=\nATLASSIAN_EMAIL=\n# OPTIONAL_TOKEN=\n';
    const { text, added } = appendEnvExampleBlock(local, upstream);
    expect(added).toEqual(['ATLASSIAN_EMAIL', 'OPTIONAL_TOKEN']);
    expect(text.startsWith(local.trimEnd())).toBe(true);
    expect(text).toContain(ADOPT_ENV_SENTINEL);
    expect(text.endsWith('ATLASSIAN_EMAIL=\n# OPTIONAL_TOKEN=\n')).toBe(true);
    // Idempotent: a second pass finds nothing missing and returns the text as is.
    expect(appendEnvExampleBlock(text, upstream)).toEqual({ text, added: [] });
  });

  test('keeps CRLF and opens no second sentinel', () => {
    const local = 'A=1\r\n';
    const first = appendEnvExampleBlock(local, 'B=\n').text;
    expect(first).toContain('\r\nB=\r\n');
    const second = appendEnvExampleBlock(first, 'B=\nC=\n').text;
    expect(second.split(ADOPT_ENV_SENTINEL).length).toBe(2);
    expect(second.endsWith('B=\r\nC=\r\n')).toBe(true);
  });
});

describe('planAdoptInstructions', () => {
  test('neither file: deliver', () => {
    expect(planAdoptInstructions(tempRoot(), UPSTREAM_AGENTS)).toEqual({ kind: 'deliver' });
  });

  test('an orphaned shim (CLAUDE.md shim, no AGENTS.md): deliver, not a blocker', () => {
    const root = tempRoot();
    write(root, 'CLAUDE.md', CLAUDE_INSTRUCTIONS_SHIM);
    expect(planAdoptInstructions(root, UPSTREAM_AGENTS)).toEqual({ kind: 'deliver' });
  });

  test('upstream AGENTS.md plus the exact shim: none; a missing shim: shim', () => {
    const root = tempRoot();
    write(root, 'AGENTS.md', UPSTREAM_AGENTS);
    expect(planAdoptInstructions(root, UPSTREAM_AGENTS)).toEqual({ kind: 'shim' });
    write(root, 'CLAUDE.md', CLAUDE_INSTRUCTIONS_SHIM);
    expect(planAdoptInstructions(root, UPSTREAM_AGENTS)).toEqual({ kind: 'none' });
  });

  test('app text in CLAUDE.md, AGENTS.md or both: one compose proposal with every source', () => {
    const root = tempRoot();
    write(root, 'CLAUDE.md', '# App memory\nUse pnpm.\n');
    expect(planAdoptInstructions(root, UPSTREAM_AGENTS)).toEqual({ kind: 'compose', sources: [{ file: 'CLAUDE.md', text: '# App memory\nUse pnpm.\n' }] });
    write(root, 'AGENTS.md', '# App agents\n');
    const plan = planAdoptInstructions(root, UPSTREAM_AGENTS);
    expect(plan.kind).toBe('compose');
    expect(plan.kind === 'compose' && plan.sources.map(s => s.file)).toEqual(['AGENTS.md', 'CLAUDE.md']);
  });
});

describe('composeAdoptedInstructions', () => {
  test('the app text sits verbatim in a ## 0. block before ## 1., the boilerplate text around it unchanged', () => {
    const app = '# App memory\n\n## Rules\n- never touch prod\n';
    const out = composeAdoptedInstructions(UPSTREAM_AGENTS, [{ file: 'CLAUDE.md', text: app }], '.backups/update-x');
    const zero = out.indexOf(ADOPT_INSTRUCTIONS_HEADING);
    expect(zero).toBeGreaterThan(out.indexOf('> header'));
    expect(zero).toBeLessThan(out.indexOf('## 1. CRITICAL RULES'));
    expect(out).toContain(app.trimEnd());
    expect(out).toContain('`.backups/update-x/`');
    expect(out.replace(/## 0\.[\s\S]*?\n---\n\n/, '')).toBe(UPSTREAM_AGENTS);
  });

  test('an upstream file with no numbered section gets the block after its title', () => {
    const out = composeAdoptedInstructions('# Title\nbody\n', [{ file: 'AGENTS.md', text: 'x' }], null);
    expect(out.startsWith(`# Title\n\n${ADOPT_INSTRUCTIONS_HEADING}`)).toBe(true);
  });
});

describe('project.yaml', () => {
  test('seeded from the schema; a template without one keeps its text with provenance reset', () => {
    expect(seedAdoptedProjectYaml('ignored', SCHEMA)).not.toContain('GENERATED');
    expect(seedAdoptedProjectYaml('ignored', SCHEMA)).toContain('project_name: null');
    const filled = 'git_strategy:\n  meta:\n    strategy_source: chosen\n';
    expect(seedAdoptedProjectYaml(filled, null)).toBe('git_strategy:\n  meta:\n    strategy_source: inherited\n');
  });

  test('withProtectedPaths fills an empty list, keeps its comment, and re-parses to exactly the paths', () => {
    const yaml = 'project:\n  a: 1\n\nupdater:\n  protected_paths: [] # e.g. [x]\n\nnext: 2\n';
    const out = withProtectedPaths(yaml, ['scripts/lint.ts', '.env.example', 'scripts/lint.ts'])!;
    expect(out).toContain('  protected_paths: # e.g. [x]\n    - ".env.example"\n    - "scripts/lint.ts"\n');
    const parsed = parseYaml(out) as { updater: { protected_paths: string[] }, next: number };
    expect(parsed.updater.protected_paths).toEqual(['.env.example', 'scripts/lint.ts']);
    expect(parsed.next).toBe(2);
  });

  test('withProtectedPaths appends an updater block when there is none, and never edits a list the project wrote', () => {
    expect(parseYaml(withProtectedPaths('a: 1\n', ['x.ts'])!)).toEqual({ a: 1, updater: { protected_paths: ['x.ts'] } });
    expect(withProtectedPaths('updater:\n  protected_paths: [mine.ts]\n', ['x.ts'])).toBeNull();
    expect(withProtectedPaths('a: 1\n', [])).toBe('a: 1\n');
  });
});

describe('installer lock', () => {
  test('adopted: true, the template handle install.ts accepts, other keys kept', () => {
    const root = tempRoot();
    expect(isAdopted(root)).toBe(false);
    write(root, INSTALLER_LOCK_FILE, '{"templateBranch":"main"}\n');
    writeInstallerLock(root);
    expect(JSON.parse(read(root, INSTALLER_LOCK_FILE))).toEqual({ templateBranch: 'main', template: CANONICAL_TEMPLATE, adopted: true });
    expect(isAdopted(root)).toBe(true);
  });
});

describe('adoptPackageJsonDelta', () => {
  const section = (upstreamOnlyKeys: Record<string, string>): PackageJsonDelta['sections'][string] => ({ upstreamOnlyKeys, localOverrideKeys: {}, localOnlyKeys: [], alreadyApplied: [] });

  test('tooling runtime packages go to devDependencies; a package the app declares anywhere is never added again', () => {
    const delta: PackageJsonDelta = {
      file: 'package.json',
      sections: {
        scripts: section({ up: 'bun cli/update-boilerplate.ts' }),
        dependencies: section({ yaml: '^2.8.2', picocolors: '^1.1.1' }),
        devDependencies: section({ typescript: '^5.9.3', husky: '^9.1.7' }),
      },
    };
    const local = { dependencies: { react: '19.0.0', typescript: '5.4.0' }, devDependencies: { picocolors: '^1.0.0' } };
    const { delta: out, satisfied } = adoptPackageJsonDelta(delta, local);
    expect(out.sections.dependencies.upstreamOnlyKeys).toEqual({});
    expect(out.sections.devDependencies.upstreamOnlyKeys).toEqual({ husky: '^9.1.7', yaml: '^2.8.2' });
    expect(out.sections.scripts.upstreamOnlyKeys).toEqual({ up: 'bun cli/update-boilerplate.ts' });
    // Remembered in their upstream section, so a later plain `up` does not add them there.
    expect(satisfied).toEqual({ dependencies: ['picocolors', 'yaml'], devDependencies: ['typescript'] });
    // Pure.
    expect(delta.sections.dependencies.upstreamOnlyKeys).toEqual({ yaml: '^2.8.2', picocolors: '^1.1.1' });
  });
});

describe('parity rows', () => {
  test('prepare and setup collisions carry a composition proposal; other scripts do not', () => {
    expect(scriptCompositionProposal('prepare', 'husky', 'husky && bun x')).toBe('"prepare": "husky && husky && bun x"');
    expect(scriptCompositionProposal('test', 'vitest', 'bun test')).toBeNull();
  });

  test('a collision blocks until it is protected; a kept script always blocks', () => {
    const root = tempRoot();
    const upstream = tempRoot();
    write(root, 'docs/README.md', 'app\n');
    write(upstream, 'docs/README.md', 'upstream\n');
    const base = { root, upstreamDir: upstream, collisions: ['docs/README.md'], envAdded: [], envCollision: false, scriptsKept: [], instructions: { kind: 'none' as const, applied: false, files: [], where: null } };
    expect(adoptFindings({ ...base, protectedWritten: false })[0]).toMatchObject({ path: 'docs/README.md', surface: 'components', suggested: 'merge', blocking: true });
    expect(adoptFindings({ ...base, protectedWritten: true })[0].blocking).toBe(false);
    const scriptRow = adoptFindings({ ...base, collisions: [], protectedWritten: true, scriptsKept: [{ file: 'package.json', section: 'scripts', key: 'prepare', localValue: 'husky', upstreamValue: 'husky && bun x', resolution: 'mine' }] })[0];
    expect(scriptRow).toMatchObject({ surface: 'package', blocking: true, suggested: 'decide' });
    expect(scriptRow.evidence).toContain('proposed: "prepare"');
  });

  test('skill files collapse into one row per skill folder', () => {
    const rows = adoptFindings({ root: tempRoot(), upstreamDir: tempRoot(), collisions: ['.agents/skills/acli/SKILL.md', '.agents/skills/acli/references/a.md'], protectedWritten: true, envAdded: [], envCollision: false, scriptsKept: [], instructions: { kind: 'none', applied: false, files: [], where: null } });
    expect(rows.map(r => [r.surface, r.path])).toEqual([['skills', '.agents/skills/acli/']]);
  });
});

describe('runAdopt', () => {
  function fixture(): { root: string, upstream: string } {
    const root = tempRoot();
    const upstream = tempRoot();
    write(upstream, 'AGENTS.md', UPSTREAM_AGENTS);
    write(upstream, '.agents/project.schema.yaml', SCHEMA);
    write(upstream, '.agents/project.yaml', 'git_strategy:\n  meta:\n    strategy_source: chosen\n');
    write(upstream, '.env.example', 'APP=\nATLASSIAN_EMAIL=\n');
    write(root, '.env.example', 'APP=real\n');
    write(root, 'CLAUDE.md', '# App memory\n');
    // What the core delivered this run: the maintainer's yaml.
    write(root, '.agents/project.yaml', read(upstream, '.agents/project.yaml'));
    return { root, upstream };
  }
  function input(root: string, upstream: string, over: Partial<AdoptHookInput> = {}): AdoptHookInput {
    return {
      root,
      upstreamDir: upstream,
      dryRun: false,
      nonInteractive: true,
      appliedPaths: ['.agents/project.yaml'],
      collisions: [{ path: '.env.example', component: 'env-template' }, { path: 'docs/README.md', component: 'docs' }],
      packageJsonKept: [],
      backupDir: null,
      confirm: async () => true,
      step: () => {},
      warn: () => {},
      ...over,
    };
  }

  test('--auto: yaml seeded with the collisions protected, env appended, lock written, instructions left pending and saved', async () => {
    const { root, upstream } = fixture();
    const out = await runAdopt(input(root, upstream));
    const yaml = read(root, '.agents/project.yaml');
    expect(yaml).toContain('project_name: null');
    expect(yaml).not.toContain('strategy_source: chosen');
    expect((parseYaml(yaml) as { updater: { protected_paths: string[] } }).updater.protected_paths).toEqual(['.env.example', 'docs/README.md']);
    expect(read(root, '.env.example')).toContain('ATLASSIAN_EMAIL=');
    expect(read(root, '.env.example').startsWith('APP=real\n')).toBe(true);
    expect(isAdopted(root)).toBe(true);
    // Never applied without a yes: CLAUDE.md untouched, AGENTS.md not created.
    expect(read(root, 'CLAUDE.md')).toBe('# App memory\n');
    expect(existsSync(join(root, 'AGENTS.md'))).toBe(false);
    expect(read(root, ADOPT_INSTRUCTIONS_PROMPT)).toContain('# App memory');
    expect(out.instructions).toMatchObject({ kind: 'compose', applied: false });
    expect(out.findings.find(f => f.surface === 'instructions')?.blocking).toBe(true);
    expect(out.findings.find(f => f.path === 'docs/README.md')?.blocking).toBe(false);
  });

  test('interactive yes: AGENTS.md composed, CLAUDE.md the shim, the original in the backup', async () => {
    const { root, upstream } = fixture();
    const out = await runAdopt(input(root, upstream, { nonInteractive: false }));
    expect(read(root, 'CLAUDE.md')).toBe(CLAUDE_INSTRUCTIONS_SHIM);
    expect(read(root, 'AGENTS.md')).toContain(`${ADOPT_INSTRUCTIONS_HEADING}`);
    expect(read(root, 'AGENTS.md')).toContain('# App memory');
    expect(read(root, join(out.instructions.where!, 'CLAUDE.md'))).toBe('# App memory\n');
    expect(out.findings.find(f => f.surface === 'instructions')?.blocking).toBe(false);
  });

  test('an app yaml that pre-existed is never edited: the collision rows block instead', async () => {
    const { root, upstream } = fixture();
    write(root, '.agents/project.yaml', 'orchestration:\n  x: 1\n');
    const out = await runAdopt(input(root, upstream, { appliedPaths: [] }));
    expect(read(root, '.agents/project.yaml')).toBe('orchestration:\n  x: 1\n');
    expect(out.protectedPaths).toEqual([]);
    expect(out.findings.find(f => f.path === 'docs/README.md')?.blocking).toBe(true);
  });

  test('--dry-run writes nothing', async () => {
    const { root, upstream } = fixture();
    rmSync(join(root, '.agents'), { recursive: true });
    const before = readdirSync(root).sort();
    const envBefore = read(root, '.env.example');
    const out = await runAdopt(input(root, upstream, { dryRun: true, appliedPaths: [] }));
    expect(readdirSync(root).sort()).toEqual(before);
    expect(read(root, '.env.example')).toBe(envBefore);
    expect(out.yamlSeeded).toBe(true);
    expect(out.protectedPaths).toEqual(['.env.example', 'docs/README.md']);
    expect(out.installerLockWritten).toBe(false);
  });

  test('no instructions anywhere: upstream AGENTS.md and the shim are delivered without asking', async () => {
    const { root, upstream } = fixture();
    rmSync(join(root, 'CLAUDE.md'));
    let asked = false;
    await runAdopt(input(root, upstream, { confirm: async () => { asked = true; return false; } }));
    expect(asked).toBe(false);
    expect(read(root, 'AGENTS.md')).toBe(UPSTREAM_AGENTS);
    expect(read(root, 'CLAUDE.md')).toBe(CLAUDE_INSTRUCTIONS_SHIM);
  });
});
